# Generated by Django 4.1.1 on 2022-09-16 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopping_list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="members",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
